export interface GeneratedFile {
  path: string;
  content: string;
  type: 'typescript' | 'solidity' | 'config' | 'markdown' | 'css';
}

export interface ProjectConfig {
  name: string;
  description: string;
  template: string;
  features: string[];
  chain: string;
}

export function generateProject(config: ProjectConfig): GeneratedFile[] {
  const { name, description, template } = config;
  const files: GeneratedFile[] = [];

  // Common files for all templates
  files.push(generatePackageJson(name, description, template));
  files.push(generateTsConfig(name));
  files.push(generateReadme(name, description, template));
  files.push(generateLayout(name));
  files.push(generateGlobalsCss());
  files.push(generateNextConfig());

  // Template-specific files
  switch (template) {
    case 'nft-marketplace':
      files.push(...generateNFTMarketplace(name));
      break;
    case 'defi-dashboard':
      files.push(...generateDeFiDashboard(name));
      break;
    case 'dao-governance':
      files.push(...generateDAOGovernance(name));
      break;
    case 'token-launch':
      files.push(...generateTokenLaunch(name));
      break;
    case 'web3-social':
      files.push(...generateWeb3Social(name));
      break;
    default:
      files.push(generateDefaultPage(name, description));
      break;
  }

  return files;
}

function generatePackageJson(name: string, description: string, template: string): GeneratedFile {
  const deps: Record<string, string> = {
    next: '16.1.6',
    react: '19.2.3',
    'react-dom': '19.2.3',
  };

  if (['nft-marketplace', 'defi-dashboard', 'dao-governance', 'token-launch'].includes(template)) {
    deps['ethers'] = '^6.13.0';
    deps['wagmi'] = '^2.14.0';
    deps['viem'] = '^2.21.0';
  }

  return {
    path: `${name}/package.json`,
    content: JSON.stringify({
      name,
      version: '0.1.0',
      private: true,
      description,
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
        lint: 'eslint',
      },
      dependencies: deps,
      devDependencies: {
        '@tailwindcss/postcss': '^4',
        '@types/node': '^20',
        '@types/react': '^19',
        '@types/react-dom': '^19',
        eslint: '^9',
        'eslint-config-next': '16.1.6',
        tailwindcss: '^4',
        typescript: '^5',
      },
    }, null, 2),
    type: 'config',
  };
}

function generateTsConfig(name: string): GeneratedFile {
  return {
    path: `${name}/tsconfig.json`,
    content: JSON.stringify({
      compilerOptions: {
        target: 'ES2017',
        lib: ['dom', 'dom.iterable', 'esnext'],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: 'esnext',
        moduleResolution: 'bundler',
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: 'preserve',
        incremental: true,
        paths: { '@/*': ['./src/*'] },
      },
      include: ['next-env.d.ts', '**/*.ts', '**/*.tsx'],
      exclude: ['node_modules'],
    }, null, 2),
    type: 'config',
  };
}

function generateReadme(name: string, description: string, template: string): GeneratedFile {
  return {
    path: `${name}/README.md`,
    content: `# ${name}\n\n${description}\n\nScaffolded by [Dockyard](https://team-dockyard.vercel.app) using the \`${template}\` template.\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\nOpen [http://localhost:3000](http://localhost:3000)\n\n## Built With\n\n- Next.js 16 + React 19\n- Tailwind CSS 4\n- TypeScript\n${['nft-marketplace', 'defi-dashboard', 'dao-governance', 'token-launch'].includes(template) ? '- Ethers.js + Wagmi\n- Solidity (OpenZeppelin v5)\n' : ''}\n---\n*Generated by Dockyard 🦞*\n`,
    type: 'markdown',
  };
}

function generateLayout(name: string): GeneratedFile {
  return {
    path: `${name}/src/app/layout.tsx`,
    content: `import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: '${name}',
  description: 'Built with Dockyard',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
`,
    type: 'typescript',
  };
}

function generateGlobalsCss(): GeneratedFile {
  return {
    path: 'globals.css',
    content: `@import "tailwindcss";\n`,
    type: 'css',
  };
}

function generateNextConfig(): GeneratedFile {
  return {
    path: 'next.config.ts',
    content: `import type { NextConfig } from "next";\nconst nextConfig: NextConfig = {};\nexport default nextConfig;\n`,
    type: 'typescript',
  };
}

function generateDefaultPage(name: string, description: string): GeneratedFile {
  return {
    path: `${name}/src/app/page.tsx`,
    content: `export default function Home() {
  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-950 text-white">
      <div className="text-center space-y-4">
        <h1 className="text-5xl font-bold">${name}</h1>
        <p className="text-gray-400">${description}</p>
        <p className="text-sm text-gray-600">Scaffolded by Dockyard 🦞</p>
      </div>
    </div>
  );
}
`,
    type: 'typescript',
  };
}

function generateNFTMarketplace(name: string): GeneratedFile[] {
  return [
    {
      path: `${name}/src/app/page.tsx`,
      content: `import Link from 'next/link';

export default function Home() {
  return (
    <div className="min-h-screen bg-gray-950 text-white p-8">
      <header className="max-w-6xl mx-auto flex justify-between items-center mb-16">
        <h1 className="text-2xl font-bold">${name}</h1>
        <nav className="flex gap-4">
          <Link href="/marketplace" className="hover:text-blue-400">Marketplace</Link>
          <button className="bg-blue-500 px-4 py-2 rounded-lg">Connect Wallet</button>
        </nav>
      </header>
      <main className="max-w-6xl mx-auto text-center space-y-8">
        <h2 className="text-5xl font-bold">Discover & Collect NFTs</h2>
        <p className="text-gray-400 max-w-xl mx-auto">The premier marketplace for unique digital assets with built-in royalties.</p>
        <Link href="/marketplace" className="inline-block bg-blue-500 px-8 py-3 rounded-lg font-medium">Explore →</Link>
      </main>
    </div>
  );
}
`,
      type: 'typescript',
    },
    {
      path: `${name}/src/app/marketplace/page.tsx`,
      content: `'use client';
export default function Marketplace() {
  const mockNFTs = Array.from({ length: 6 }, (_, i) => ({
    id: i + 1,
    name: \`NFT #\${i + 1}\`,
    price: (Math.random() * 2).toFixed(3),
  }));
  return (
    <div className="min-h-screen bg-gray-950 text-white p-8">
      <h1 className="text-3xl font-bold mb-8">Marketplace</h1>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {mockNFTs.map((nft) => (
          <div key={nft.id} className="bg-gray-900 rounded-xl p-4 border border-gray-800">
            <div className="aspect-square bg-gradient-to-br from-purple-500 to-blue-500 rounded-lg mb-4" />
            <h3 className="font-semibold">{nft.name}</h3>
            <p className="text-blue-400">{nft.price} ETH</p>
          </div>
        ))}
      </div>
    </div>
  );
}
`,
      type: 'typescript',
    },
    {
      path: `${name}/contracts/NFTMarketplace.sol`,
      content: `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC721/extensions/ERC721Enumerable.sol";
import "@openzeppelin/contracts/token/common/ERC2981.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

contract ${name.replace(/[^a-zA-Z]/g, '')}NFT is ERC721Enumerable, ERC2981, Ownable {
    uint256 public constant MAX_SUPPLY = 10000;
    uint256 public constant MINT_PRICE = 0.01 ether;
    uint256 private _nextTokenId;

    constructor(address initialOwner)
        ERC721("${name}", "NFT")
        Ownable(initialOwner)
    {
        _setDefaultRoyalty(initialOwner, 500); // 5%
    }

    function mint(uint256 quantity) external payable {
        require(_nextTokenId + quantity <= MAX_SUPPLY, "Exceeds max supply");
        require(msg.value >= MINT_PRICE * quantity, "Insufficient payment");
        for (uint256 i = 0; i < quantity; i++) {
            _safeMint(msg.sender, _nextTokenId++);
        }
    }

    function withdraw() external onlyOwner {
        (bool s, ) = payable(owner()).call{value: address(this).balance}("");
        require(s);
    }

    function supportsInterface(bytes4 interfaceId)
        public view override(ERC721Enumerable, ERC2981) returns (bool)
    {
        return super.supportsInterface(interfaceId);
    }
}
`,
      type: 'solidity',
    },
  ];
}

function generateDeFiDashboard(name: string): GeneratedFile[] {
  return [
    {
      path: `${name}/src/app/page.tsx`,
      content: `export default function Home() {
  return (
    <div className="min-h-screen bg-gray-950 text-white p-8">
      <h1 className="text-3xl font-bold mb-8">📊 ${name}</h1>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
        <div className="bg-gray-900 rounded-xl p-6 border border-gray-800">
          <p className="text-gray-400 text-sm">Total Value</p>
          <p className="text-3xl font-bold">$12,345.67</p>
        </div>
        <div className="bg-gray-900 rounded-xl p-6 border border-gray-800">
          <p className="text-gray-400 text-sm">24h Change</p>
          <p className="text-3xl font-bold text-green-400">+5.2%</p>
        </div>
        <div className="bg-gray-900 rounded-xl p-6 border border-gray-800">
          <p className="text-gray-400 text-sm">Assets</p>
          <p className="text-3xl font-bold">7</p>
        </div>
      </div>
    </div>
  );
}
`,
      type: 'typescript',
    },
  ];
}

function generateDAOGovernance(name: string): GeneratedFile[] {
  return [
    {
      path: `${name}/src/app/page.tsx`,
      content: `export default function Home() {
  return (
    <div className="min-h-screen bg-gray-950 text-white p-8">
      <h1 className="text-3xl font-bold mb-8">🏛️ ${name}</h1>
      <div className="max-w-2xl space-y-4">
        {[1, 2, 3].map((i) => (
          <div key={i} className="bg-gray-900 rounded-xl p-6 border border-gray-800">
            <div className="flex justify-between items-center mb-2">
              <h3 className="font-semibold">Proposal #{i}</h3>
              <span className="text-xs bg-green-500/20 text-green-400 px-2 py-1 rounded">Active</span>
            </div>
            <p className="text-gray-400 text-sm mb-4">Example governance proposal</p>
            <div className="flex gap-3">
              <button className="bg-green-600 px-4 py-2 rounded-lg text-sm">Vote For</button>
              <button className="bg-red-600 px-4 py-2 rounded-lg text-sm">Vote Against</button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
`,
      type: 'typescript',
    },
  ];
}

function generateTokenLaunch(name: string): GeneratedFile[] {
  return [
    {
      path: `${name}/src/app/page.tsx`,
      content: `export default function Home() {
  return (
    <div className="min-h-screen bg-gray-950 text-white p-8">
      <div className="max-w-2xl mx-auto text-center space-y-8 py-20">
        <h1 className="text-5xl font-bold">🚀 ${name}</h1>
        <p className="text-gray-400">Your token launch platform</p>
        <div className="bg-gray-900 rounded-xl p-8 border border-gray-800 text-left space-y-4">
          <div><label className="text-sm text-gray-400">Token Name</label><input className="w-full bg-gray-800 rounded px-4 py-2 mt-1" /></div>
          <div><label className="text-sm text-gray-400">Symbol</label><input className="w-full bg-gray-800 rounded px-4 py-2 mt-1" /></div>
          <div><label className="text-sm text-gray-400">Initial Supply</label><input className="w-full bg-gray-800 rounded px-4 py-2 mt-1" /></div>
          <button className="w-full bg-blue-500 py-3 rounded-lg font-medium">Deploy Token</button>
        </div>
      </div>
    </div>
  );
}
`,
      type: 'typescript',
    },
  ];
}

function generateWeb3Social(name: string): GeneratedFile[] {
  return [
    {
      path: `${name}/src/app/page.tsx`,
      content: `export default function Home() {
  return (
    <div className="min-h-screen bg-gray-950 text-white p-8">
      <h1 className="text-3xl font-bold mb-8">💬 ${name}</h1>
      <div className="max-w-xl space-y-4">
        <div className="bg-gray-900 rounded-xl p-4 border border-gray-800">
          <textarea className="w-full bg-transparent resize-none" placeholder="What's on your mind?" rows={3} />
          <button className="bg-blue-500 px-4 py-2 rounded-lg text-sm mt-2">Post</button>
        </div>
        {[1, 2, 3].map((i) => (
          <div key={i} className="bg-gray-900 rounded-xl p-4 border border-gray-800">
            <div className="flex items-center gap-2 mb-2">
              <div className="w-8 h-8 bg-blue-500 rounded-full" />
              <span className="font-medium">user.eth</span>
            </div>
            <p className="text-gray-300">Example post #{i} on the decentralized feed.</p>
          </div>
        ))}
      </div>
    </div>
  );
}
`,
      type: 'typescript',
    },
  ];
}
